version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 122090430541.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t tutorial5 .
      - docker tag tutorial5:latest 122090430541.dkr.ecr.us-east-1.amazonaws.com/tutorial5:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 122090430541.dkr.ecr.us-east-1.amazonaws.com/tutorial5:latest
      - echo Writing Image Definitions file...
      - printf '[{"name":"Container-app-python","imageUri":"122090430541.dkr.ecr.us-east-1.amazonaws.com/tutorial5:latest"}]' > imagedefinitions.json
      - printf '{"ImageURI":"122090430541.dkr.ecr.us-east-1.amazonaws.com/tutorial5:latest"}' > imageDetail.json
      - cat imagedefinitions.json 
artifacts:
  files:
    - '**/*'
    - imagedefinitions.json
    - imageDetail.json
  secondary-artifacts:
    DefinitionArtifact:
      files:
        - appspec.yaml
        - taskdef.json
    ImageArtifact:
      files:
        - imageDetail.json